#version 450

struct TipData {
    uint maxDistBits;
    uint tipIndex;
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 0, binding = 1) buffer OutPoints { vec2 points[]; };
layout(std430, set = 0, binding = 2) buffer Counter { uint count[]; };
layout(std430, set = 0, binding = 4) buffer KNN { uint knn[]; };
layout (std430, set = 0, binding = 5) buffer TipInfo { TipData tips[]; };

layout(push_constant) uniform Push {
    uint maxPoints;                     
    layout(offset = 16) vec3 normal;    
    layout(offset = 32) vec3 point;     
    layout(offset = 48) vec4 mapInfo;   
    layout(offset = 64) int isRightCut; 
} push;

// 💥 申请 16KB 的极速片内共享内存
shared vec2 sharedPoints[2048]; 

void main()
{
    uint i = gl_GlobalInvocationID.x;   
    uint plnIdx = uint(gl_GlobalInvocationID.z);
    uint validCount = count[plnIdx];
    
    // 💥 协作加载：让当前工作组的 256 个线程一起把数据从慢速 SSBO 搬进极速 Shared 内存
    uint localId = gl_LocalInvocationID.x;
    for (uint idx = localId; idx < validCount && idx < 2048; idx += 256) {
        sharedPoints[idx] = points[plnIdx * push.maxPoints + idx];
    }
    
    // 必须等待所有线程都搬运完毕！
    barrier();

    if (i >= validCount) return;

    vec2 p = sharedPoints[i];

    float d0 = 9999., d1 = 9999., d2 = 9999., d3 = 9999.;
    uint n0 = i, n1 = i, n2 = i, n3 = i;
    for (uint j = 0; j < validCount; j++) {
        if (i == j) continue;

        // 💥 从极速共享内存中读取！这直接决定了 Shader 的生死速度！
        vec2 pj = sharedPoints[j];
        float d = dot(p - pj, p - pj);

        if (d < d0) {
            d3 = d2; n3 = n2;
            d2 = d1; n2 = n1;
            d1 = d0; n1 = n0;
            d0 = d;  n0 = j;
        } else if (d < d1) {
            d3 = d2; n3 = n2;
            d2 = d1; n2 = n1;
            d1 = d;  n1 = j;
        } else if (d < d2) {
            d3 = d2; n3 = n2;
            d2 = d;  n2 = j;
        } else if (d < d3) {
            d3 = d;  n3 = j;
        }
    }

    uint knnBase = plnIdx * push.maxPoints * 4 + i * 4;
    knn[knnBase + 0] = n0;
    knn[knnBase + 1] = n1;
    knn[knnBase + 2] = n2;
    knn[knnBase + 3] = n3;
}