#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0) uniform usampler2D inputMask;

struct BBox {
    uint minX;
    uint minY;
    uint maxX;
    uint maxY;
};

// 记录全局最小/最大像素坐标
layout (std430, binding = 1) buffer BBoxBuffer {
    BBox bboxes[];
};

layout(push_constant) uniform PushConstants {
    uint planeIdx;
} push;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = textureSize(inputMask, 0);

    if (pos.x >= size.x || pos.y >= size.y) {
        return;
    }

    uint val = texelFetch(inputMask, pos, 0).r;

    if (val == 3u) {
        atomicMin(bboxes[push.planeIdx].minX, pos.x);
        atomicMin(bboxes[push.planeIdx].minY, pos.y);
        atomicMax(bboxes[push.planeIdx].maxX, pos.x);
        atomicMax(bboxes[push.planeIdx].maxY, pos.y);
    }
}