#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

const uint ZMAP_RESOLUTION = 7200;
const float PI = 3.14159265359;

struct Triangle { vec4 v0; vec4 v1; vec4 v2; };

struct PoseData {
    mat4 modelMatrix;
    vec4 projU;
    vec4 projV;
};

layout(std430, set = 0, binding = 0) readonly buffer TriBuffer { 
    Triangle triangles[]; 
};

layout(std430, set = 0, binding = 1) buffer ZMapBuffer { 
    uint zMap[]; 
};

layout(std430, set = 0, binding = 2) readonly buffer BasePose { 
    PoseData poses[]; 
};

layout(push_constant) uniform PushConstants {
    layout(offset = 0) vec3 planeNormal;
    layout(offset = 16) vec3 planePoint;
    layout(offset = 32) vec3 planeU;
    layout(offset = 48) vec3 planeV;
    layout(offset = 64) float stepX;
    layout(offset = 68) float tanHelixAngle;
    layout(offset = 72) float radius;
    layout(offset = 76) uint stepsPerPose;
    layout(offset = 80) uint numTriangles;
    layout(offset = 84) uint curBatchSize;  // 当前粒子数
} push;

shared mat4 s_finalModel;
shared vec3 s_projU;
shared vec3 s_projV;
shared vec3 s_localPlaneNorm;
shared vec3 s_localPlanePoint;


void main() {
    uint triIdx = gl_GlobalInvocationID.x;
    uint stepIdx = gl_GlobalInvocationID.y;
    uint poseIdx = gl_GlobalInvocationID.z;
    uint localIdx = gl_LocalInvocationID.x; // 砂轮中的256个三角形id

    uint halfSize = zMap.length() / 2;

    if(localIdx == 0) {
        float stepDist = float(stepIdx) * push.stepX;
        float theta = (stepDist * push.tanHelixAngle) / push.radius;
        
        // 构建局部平移和旋转矩阵
        mat4 transX = mat4(1.0); transX[3][0] = stepDist;
        mat4 rotX = mat4(1.0, 0.0, 0.0, 0.0,
                        0.0, cos(theta), sin(theta), 0.0,
                        0.0, -sin(theta), cos(theta), 0.0,
                        0.0, 0.0, 0.0, 1.0);

        mat4 finalModel = (transX * rotX) * poses[poseIdx].modelMatrix;
        s_finalModel = finalModel;
        s_projU = poses[poseIdx].projU.xyz;
        s_projV = poses[poseIdx].projV.xyz;

        // 只有 0 号线程执行 1 次 inverse
        mat4 invModel = inverse(finalModel);
        s_localPlaneNorm = normalize((invModel * vec4(push.planeNormal, 0.0)).xyz);
        s_localPlanePoint = (invModel * vec4(push.planePoint, 1.0)).xyz;
    }

    barrier();

    // 确保没有越界的线程，保证不会写出界
    bool validWork = (triIdx < push.numTriangles) && (stepIdx < push.stepsPerPose) && (poseIdx < push.curBatchSize);

    if (validWork) {
        Triangle tri = triangles[triIdx];

        float d0 = dot(tri.v0.xyz - s_localPlanePoint, s_localPlaneNorm);
        float d1 = dot(tri.v1.xyz - s_localPlanePoint, s_localPlaneNorm);
        float d2 = dot(tri.v2.xyz - s_localPlanePoint, s_localPlaneNorm);

        bool crossPlane = !((d0 > 0.0 && d1 > 0.0 && d2 > 0.0) || (d0 < 0.0 && d1 < 0.0 && d2 < 0.0));
        
        if (crossPlane) {
            bool s0 = d0 >= 0.0;
            bool s1 = d1 >= 0.0; 
            bool s2 = d2 >= 0.0;
            vec3 pA_local, pB_local;

            if (s0 == s1) { 
                pA_local = mix(tri.v2.xyz, tri.v0.xyz, d2/(d2-d0));
                pB_local = mix(tri.v2.xyz, tri.v1.xyz, d2/(d2-d1)); 
            } else if (s0 == s2) { 
                pA_local = mix(tri.v1.xyz, tri.v0.xyz, d1/(d1-d0));
                pB_local = mix(tri.v1.xyz, tri.v2.xyz, d1/(d1-d2)); 
            } else {
                pA_local = mix(tri.v0.xyz, tri.v1.xyz, d0/(d0-d1));
                pB_local = mix(tri.v0.xyz, tri.v2.xyz, d0/(d0-d2));
            }

            vec3 pA = (s_finalModel * vec4(pA_local, 1.0)).xyz;
            vec3 pB = (s_finalModel * vec4(pB_local, 1.0)).xyz;

            vec3 projU = s_projU;
            vec3 projV = s_projV;
            vec2 p2A = vec2(dot(pA - push.planePoint, projU), dot(pA - push.planePoint, projV));
            vec2 p2B = vec2(dot(pB - push.planePoint, projU), dot(pB - push.planePoint, projV));

            bool inFront = (p2A.x > -0.1 || p2B.x > -0.1);
            
            if (inFront) {
                // 剔除了后半区，thetaA和thetaB被限制在[-PI/2, PI/2]
                float thA = atan(p2A.y, p2A.x);
                float thB = atan(p2B.y, p2B.x);
                float fIdxA = (thA + PI / 2.0) / PI * float(ZMAP_RESOLUTION);
                float fIdxB = (thB + PI / 2.0) / PI * float(ZMAP_RESOLUTION);

                int startIdx = int(floor(min(fIdxA, fIdxB)));
                int endIdx = int(ceil(max(fIdxA, fIdxB)));

                startIdx = clamp(startIdx, 0, int(ZMAP_RESOLUTION) - 1);
                    endIdx = clamp(endIdx, 0, int(ZMAP_RESOLUTION) - 1);

                vec2 AB = p2B - p2A;
                float dotABAB = max(dot(AB, AB), 1e-8);
                float invDotABAB = 1. / dotABAB;

                float crossP = p2A.x * p2B.y - p2B.x * p2A.y;

                float dy = p2A.y - p2B.y;
                float dx = p2B.x - p2A.x;

                float dot_p2A_AB = dot(p2A, AB);
                

                float invZRes = PI / float(ZMAP_RESOLUTION);
                float startTh = float(startIdx) * invZRes - (PI / 2.);

                vec2 currentDir = vec2(cos(startTh), sin(startTh));
                float cosStep = cos(invZRes);
                float sinStep = sin(invZRes);

                for (int i = startIdx; i <= endIdx; i++) {

                    float denom = currentDir.x * dy + currentDir.y * dx;
                    
                    if (abs(denom) > 1e-6) {
                        float r = -crossP / denom;
                        if (r > 0.0 && r < 99998.0) {
                            float dir_dot_AB = dot(currentDir, AB);
                            float t = (r * dir_dot_AB - dot_p2A_AB) * invDotABAB;

                            if (t >= -0.00001 && t <= 1.00001) {
                                uint val = floatBitsToUint(r);
                                uint baseIdx = poseIdx * ZMAP_RESOLUTION + uint(i);

                                // 抛弃 Shared Memory，依靠连续内存的 L2 缓存原生加速！
                                atomicMin(zMap[baseIdx], val);
                                atomicMax(zMap[baseIdx + halfSize], val);
                            }
                        }
                    }

                    float nextX = currentDir.x * cosStep - currentDir.y * sinStep;
                    float nextY = currentDir.x * sinStep + currentDir.y * cosStep;
                    currentDir = vec2(nextX, nextY);

                }
            }
        }
    }
}