#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

const uint ZMAP_RESOLUTION = 7200;
const float PI = 3.14159265359;

struct Triangle { vec4 v0; vec4 v1; vec4 v2; };

struct PoseData {
    mat4 modelMatrix;
    vec4 projU;
    vec4 projV;
};

layout(std430, set = 0, binding = 0) readonly buffer TriBuffer { 
    Triangle triangles[]; 
};

layout(std430, set = 0, binding = 1) buffer ZMapBuffer { 
    uint zMap[]; 
};

layout(std430, set = 0, binding = 2) readonly buffer BasePose { 
    PoseData poses[]; 
};

layout(push_constant) uniform PushConstants {
    layout(offset = 0) vec3 planeNormal;
    layout(offset = 16) vec3 planePoint;
    layout(offset = 32) vec3 planeU;
    layout(offset = 48) vec3 planeV;
    layout(offset = 64) float stepX;
    layout(offset = 68) float tanHelixAngle;
    layout(offset = 72) float radius;
    layout(offset = 76) uint stepsPerPose;
    layout(offset = 80) uint numTriangles;
    layout(offset = 84) uint curBatchSize;  // 当前粒子数
} push;

void main() {
    uint triIdx = gl_GlobalInvocationID.x;
    uint stepIdx = gl_GlobalInvocationID.y;
    uint poseIdx = gl_GlobalInvocationID.z;

    uint halfSize = zMap.length() / 2;

    float stepDist = float(stepIdx) * push.stepX;
    float theta = (stepDist * push.tanHelixAngle) / push.radius;
    
    // 构建局部平移和旋转矩阵
    mat4 transX = mat4(1.0); transX[3][0] = stepDist;
    mat4 rotX = mat4(1.0, 0.0, 0.0, 0.0,
                     0.0, cos(theta), sin(theta), 0.0,
                     0.0, -sin(theta), cos(theta), 0.0,
                     0.0, 0.0, 0.0, 1.0);

    mat4 finalModel = (transX * rotX) * poses[poseIdx].modelMatrix;
    vec3 projU = poses[poseIdx].projU.xyz;
    vec3 projV = poses[poseIdx].projV.xyz;

    // 确保没有越界的线程，保证不会写出界
    bool validWork = (triIdx < push.numTriangles) && (stepIdx < push.stepsPerPose) && (poseIdx < push.curBatchSize);

    if (validWork) {
        Triangle tri = triangles[triIdx];
        vec3 v0 = (finalModel * tri.v0).xyz;
        vec3 v1 = (finalModel * tri.v1).xyz;
        vec3 v2 = (finalModel * tri.v2).xyz;

        float d0 = dot(v0 - push.planePoint, push.planeNormal);
        float d1 = dot(v1 - push.planePoint, push.planeNormal);
        float d2 = dot(v2 - push.planePoint, push.planeNormal);

        bool crossPlane = !((d0 > 0.0 && d1 > 0.0 && d2 > 0.0) || (d0 < 0.0 && d1 < 0.0 && d2 < 0.0));
        
        if (crossPlane) {
            bool s0 = d0 >= 0.0; bool s1 = d1 >= 0.0; bool s2 = d2 >= 0.0;
            vec3 pA, pB;
            if (s0 == s1) { 
                pA = mix(v2, v0, d2/(d2-d0)); pB = mix(v2, v1, d2/(d2-d1)); 
            } else if (s0 == s2) { 
                pA = mix(v1, v0, d1/(d1-d0)); pB = mix(v1, v2, d1/(d1-d2)); 
            } else {
                pA = mix(v0, v1, d0/(d0-d1)); pB = mix(v0, v2, d0/(d0-d2));
            }

            vec2 p2A = vec2(dot(pA - push.planePoint, projU), dot(pA - push.planePoint, projV));
            vec2 p2B = vec2(dot(pB - push.planePoint, projU), dot(pB - push.planePoint, projV));

            bool inFront = (p2A.x > -0.1 || p2B.x > -0.1);
            
            if (inFront) {
                // 剔除了后半区，thetaA和thetaB被限制在[-PI/2, PI/2]
                float thA = atan(p2A.y, p2A.x);
                float thB = atan(p2B.y, p2B.x);
                float fIdxA = (thA + PI / 2.0) / PI * float(ZMAP_RESOLUTION);
                float fIdxB = (thB + PI / 2.0) / PI * float(ZMAP_RESOLUTION);

                int startIdx = int(floor(min(fIdxA, fIdxB)));
                int endIdx = int(ceil(max(fIdxA, fIdxB)));

                startIdx = clamp(startIdx, 0, int(ZMAP_RESOLUTION) - 1);
                    endIdx = clamp(endIdx, 0, int(ZMAP_RESOLUTION) - 1);

                vec2 AB = p2B - p2A;
                float dotABAB = dot(AB, AB);
                float crossP = p2A.x * p2B.y - p2B.x * p2A.y;
                float dy = p2A.y - p2B.y;
                float dx = p2B.x - p2A.x;

                float amplitude = length(vec2(dx, dy));
                float phase = atan(dx, dy); 
                float invZRes = PI / float(ZMAP_RESOLUTION);
                float startTh = float(startIdx) * invZRes - (PI / 2.0);

                // vec2 currentDir = vec2(cos(startTh), sin(startTh));
                float cosPhase = cos(phase);
                float sinPhase = sin(phase);

                for (int i = startIdx; i <= endIdx; i++) {

                    float curTh = float(i) * invZRes - (PI / 2.0);
                    vec2 currentDir = vec2(cos(curTh), sin(curTh));

                    float denom = amplitude * (currentDir.x * cosPhase + currentDir.y * sinPhase);
                    
                    if (abs(denom) > 1e-6) {
                        float r = -crossP / denom;
                        if (r > 0.0 && r < 99998.0) {
                            vec2 AP = r * currentDir - p2A;
                            float t = dot(AP, AB) / dotABAB;

                            if (t >= -0.00001 && t <= 1.00001) {
                                uint val = floatBitsToUint(r);
                                uint baseIdx = poseIdx * ZMAP_RESOLUTION + uint(i);

                                // 抛弃 Shared Memory，依靠连续内存的 L2 缓存原生加速！
                                atomicMin(zMap[baseIdx], val);
                                atomicMax(zMap[baseIdx + halfSize], val);
                            }
                        }
                    }
                }
            }
        }
    }
}