#version 450

#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct BestResultData {
    float coreRadius;
    float slotAngle;
    float score;
    uint bestPoseIdx;
    mat4 bestMatrix;
};

layout(std430, set = 0, binding = 3) readonly buffer OutputBuffer { 
    BestResultData results[]; 
};

layout(std430, set = 0, binding = 4) buffer GlobalBestBuffer { 
    BestResultData gBest[]; 
};

layout(push_constant) uniform Push {
    layout(offset = 0) vec3 planeNormal;
    layout(offset = 16) vec3 planePoint;
    layout(offset = 32) vec3 planeU;
    layout(offset = 48) vec3 planeV;
    layout(offset = 64) float stepX;
    layout(offset = 68) float tanHelixAngle;
    layout(offset = 72) float radius;
    layout(offset = 76) uint stepsPerPose;
    layout(offset = 80) uint numTriangles;
    layout(offset = 84) uint curBatchSize;
} push;

// 用于 Subgroup 之间的通讯
shared float s_subgroupScores[16];
shared uint  s_subgroupIndices[16];

void main() 
{
    uint tid = gl_LocalInvocationID.x;

    float localMaxScore = -9999999.0;
    uint localBestIdx = 0;

    for (uint i = tid; i < push.curBatchSize; i += 256) {
        float s = results[i].score;
        if (s > localMaxScore) {
            localMaxScore = s;
            localBestIdx = i;
        }
    }

    // --- subgroup内部归约 ---
    float sgMaxScore = subgroupMax(localMaxScore);  // 当前subgroup中的最高分数

    // 找出持有最高分数的id（可能有多个，取ID最小的）
    uvec4 ballot = subgroupBallot(localMaxScore == sgMaxScore);
    uint winnerLane = subgroupBallotFindLSB(ballot);

    if(gl_SubgroupInvocationID == winnerLane) {
        s_subgroupScores[gl_SubgroupID] = sgMaxScore;
        s_subgroupIndices[gl_SubgroupID] = localBestIdx;
    }

    barrier();

    // --- 0号subgroup收尾 ---
    if(gl_SubgroupID == 0) {
        float finalScore = -9999999.;
        uint finalIdx = 0;

        if(gl_SubgroupInvocationID < gl_NumSubgroups) {
            finalScore = s_subgroupScores[gl_SubgroupInvocationID];
            finalIdx = s_subgroupIndices[gl_SubgroupInvocationID];
        }

        float totalMaxScore = subgroupMax(finalScore);
        uvec4 finalBallot = subgroupBallot(finalScore == totalMaxScore);
        uint finalWinnerLane = subgroupBallotFindLSB(finalBallot);

        if (gl_SubgroupInvocationID == finalWinnerLane) {
            // PSO 核心逻辑：只有新成绩比历史最高分还高，才更新 gBest！
            // 防止算法在寻优过程中发生退化
            if (totalMaxScore > gBest[0].score) {
                gBest[0] = results[finalIdx];
            }
        }
    }
}