#version 450

struct TipData {
    uint maxDistBits;
    uint tipIndex;
};

layout(local_size_x = 256) in;  // 每个工作组有256个线程

// binding = 1: 轮廓点buffer
layout(std430, set = 0, binding = 1) buffer OutPoints {
    vec2 points[];
};

// binding = 2: 第一阶段提取出的点数量
layout(std430, set = 0, binding = 2) buffer Counter {
    uint count[];
};

// 存储每个点最近的4个邻居索引
layout(std430, set = 0, binding = 4) buffer KNN {
    uint knn[];
};

// 存储最远点信息
layout (std430, set = 0, binding = 5) buffer TipInfo {
    TipData tips[];
};

layout(push_constant) uniform Push {
    uint maxPoints;
    uint planeIndex;
    vec3 normal;
    vec3 point;
    vec4 mapInfo;
    int isRightCut;
} push;

void main()
{
    uint i = gl_GlobalInvocationID.x;   // 当前执行线程在整个grid中的索引
    uint plnIdx = push.planeIndex;
    uint validCount = count[plnIdx];
    if (i >= validCount) return;

    uint global_i = plnIdx * push.maxPoints + i;
    vec2 p = points[global_i];

    // --- 寻找当前点最近的4个邻居 ---
    float d0 = 9999., d1 = 9999., d2 = 9999., d3 = 9999.;
    uint n0 = i, n1 = i, n2 = i, n3 = i;
    for (uint j = 0; j < validCount; j++) {
        if (i == j) continue;

        uint global_j = plnIdx * push.maxPoints + j;
        float d = dot(p - points[global_j], p - points[global_j]);

        if (d < d0) {
            d3 = d2; n3 = n2;
            d2 = d1; n2 = n1;
            d1 = d0; n1 = n0;
            d0 = d;  n0 = j;
        } else if (d < d1) {
            d3 = d2; n3 = n2;
            d2 = d1; n2 = n1;
            d1 = d;  n1 = j;
        } else if (d < d2) {
            d3 = d2; n3 = n2;
            d2 = d;  n2 = j;
        } else if (d < d3) {
            d3 = d; n3 = j;
        }
    }

    // --- 写入KNN拓扑表 ---
    uint knnBase = plnIdx * push.maxPoints * 4 + i * 4;
    knn[knnBase + 0] = n0;
    knn[knnBase + 1] = n1;
    knn[knnBase + 2] = n2;
    knn[knnBase + 3] = n3;
}